using System.Xml;

namespace XML_03
{
    class Program
    {
        static void Main(string[] args)
        {
            XmlWriterSettings settings = new XmlWriterSettings();
            settings.Indent = true;
            using (XmlWriter writer = XmlWriter.Create(@"Data.xml", settings))
            {
                writer.WriteStartDocument();
                writer.WriteComment("This file is generated by the program.");

                writer.WriteStartElement("Product");
                writer.WriteAttributeString("ID", "001");
                writer.WriteAttributeString("Name", "Keyboard");
                writer.WriteElementString("Price", "10.00");
                writer.WriteStartElement("OtherDetails");
                writer.WriteElementString("BrandName", "X Keyboard");
                writer.WriteElementString("Manufacturer", "X Company");
                writer.WriteEndElement();
                writer.WriteEndDocument();
                writer.Flush();
            }
        }
    }
}
