// <auto-generated />
using System;
using FamilyApp_2019_10_12;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVC_Core_FamilyApp_2019_10_12_Sqlite.Migrations
{
    [DbContext(typeof(FamilyDbContext))]
    partial class FamilyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("FamilyApp_2019_10_12.DadDailyItem", b =>
                {
                    b.Property<int>("DadDailyItemId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("CallChrista550");

                    b.Property<bool>("CallPhilip550");

                    b.Property<bool>("GetEarlyTrain");

                    b.Property<bool>("HitTheGym");

                    b.Property<DateTime>("TodaysDate");

                    b.Property<bool>("UpOnTime");

                    b.Property<bool>("WorkAtFinsburyPark");

                    b.HasKey("DadDailyItemId");

                    b.ToTable("DadDailyItems");

                    b.HasData(
                        new { DadDailyItemId = 1, CallChrista550 = false, CallPhilip550 = false, GetEarlyTrain = false, HitTheGym = false, TodaysDate = new DateTime(2019, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), UpOnTime = false, WorkAtFinsburyPark = false }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
