// <auto-generated />
namespace MVC_User_Login.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatedisplaynames : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedisplaynames));
        
        string IMigrationMetadata.Id
        {
            get { return "201908110743398_update-display-names"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
