// <auto-generated />
using API_2019_09_19_API_Core_From_Scratch.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API_2019_09_19_API_Core_From_Scratch.Migrations
{
    [DbContext(typeof(ToDoDbContext))]
    partial class ToDoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("API_2019_09_19_API_Core_From_Scratch.Models.ToDo", b =>
                {
                    b.Property<long>("ToDoId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("ToDoDone");

                    b.Property<string>("ToDoItem");

                    b.HasKey("ToDoId");

                    b.ToTable("ToDoes");

                    b.HasData(
                        new { ToDoId = 1L, ToDoDone = false, ToDoItem = "Test" },
                        new { ToDoId = 2L, ToDoDone = false, ToDoItem = "DoThis" },
                        new { ToDoId = 3L, ToDoDone = true, ToDoItem = "Do That" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
