// <auto-generated />
using System;
using EFCore_12_Samurai_01.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCore_12_Samurai_01.Migrations
{
    [DbContext(typeof(UserDatabaseContext))]
    [Migration("20200221131841_adding_seed_data_users_companies_categories")]
    partial class adding_seed_data_users_companies_categories
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFCore_12_Samurai_01.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Admin"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "User"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Personal"
                        });
                });

            modelBuilder.Entity("EFCore_12_Samurai_01.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            CompanyId = 1,
                            CompanyName = "Sparta"
                        },
                        new
                        {
                            CompanyId = 2,
                            CompanyName = "BBC"
                        },
                        new
                        {
                            CompanyId = 3,
                            CompanyName = "ITV"
                        });
                });

            modelBuilder.Entity("EFCore_12_Samurai_01.Models.FirstModel", b =>
                {
                    b.Property<int>("FirstModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstModelName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FirstModelId");

                    b.ToTable("FirstModels");

                    b.HasData(
                        new
                        {
                            FirstModelId = 1,
                            FirstModelName = "test one"
                        },
                        new
                        {
                            FirstModelId = 2,
                            FirstModelName = "test two"
                        },
                        new
                        {
                            FirstModelId = 3,
                            FirstModelName = "test three"
                        });
                });

            modelBuilder.Entity("EFCore_12_Samurai_01.Models.FirstModelSecondModelJoiningTable", b =>
                {
                    b.Property<int>("FirstModelId")
                        .HasColumnType("int");

                    b.Property<int>("SecondModelId")
                        .HasColumnType("int");

                    b.HasKey("FirstModelId", "SecondModelId");

                    b.HasIndex("SecondModelId");

                    b.ToTable("JoiningTable");

                    b.HasData(
                        new
                        {
                            FirstModelId = 1,
                            SecondModelId = 1
                        },
                        new
                        {
                            FirstModelId = 2,
                            SecondModelId = 2
                        },
                        new
                        {
                            FirstModelId = 3,
                            SecondModelId = 3
                        });
                });

            modelBuilder.Entity("EFCore_12_Samurai_01.Models.MainItem", b =>
                {
                    b.Property<int>("MainItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MainItemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubItemId")
                        .HasColumnType("int");

                    b.HasKey("MainItemId");

                    b.HasIndex("SubItemId");

                    b.ToTable("MainItems");
                });

            modelBuilder.Entity("EFCore_12_Samurai_01.Models.SecondModel", b =>
                {
                    b.Property<int>("SecondModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SecondModelName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SecondModelId");

                    b.ToTable("SecondModels");

                    b.HasData(
                        new
                        {
                            SecondModelId = 1,
                            SecondModelName = "test one"
                        },
                        new
                        {
                            SecondModelId = 2,
                            SecondModelName = "test two"
                        },
                        new
                        {
                            SecondModelId = 3,
                            SecondModelName = "test three"
                        });
                });

            modelBuilder.Entity("EFCore_12_Samurai_01.Models.SubItem", b =>
                {
                    b.Property<int>("SubItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SubItemName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubItemId");

                    b.ToTable("SubItems");

                    b.HasData(
                        new
                        {
                            SubItemId = 1,
                            SubItemName = "some sub item name"
                        });
                });

            modelBuilder.Entity("EFCore_12_Samurai_01.Models.Testing", b =>
                {
                    b.Property<int>("TestingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TestingName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TestingId");

                    b.ToTable("Testings");
                });

            modelBuilder.Entity("EFCore_12_Samurai_01.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CategoryId = 1,
                            CompanyId = 1,
                            UserName = "Bob"
                        },
                        new
                        {
                            UserId = 2,
                            CategoryId = 2,
                            CompanyId = 2,
                            UserName = "Tim"
                        },
                        new
                        {
                            UserId = 3,
                            CategoryId = 3,
                            CompanyId = 3,
                            UserName = "Joe"
                        });
                });

            modelBuilder.Entity("EFCore_12_Samurai_01.Models.FirstModelSecondModelJoiningTable", b =>
                {
                    b.HasOne("EFCore_12_Samurai_01.Models.FirstModel", "FirstModel")
                        .WithMany("JoiningTable")
                        .HasForeignKey("FirstModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCore_12_Samurai_01.Models.SecondModel", "SecondModel")
                        .WithMany("JoiningTable")
                        .HasForeignKey("SecondModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFCore_12_Samurai_01.Models.MainItem", b =>
                {
                    b.HasOne("EFCore_12_Samurai_01.Models.SubItem", "SubItem")
                        .WithMany()
                        .HasForeignKey("SubItemId");
                });

            modelBuilder.Entity("EFCore_12_Samurai_01.Models.User", b =>
                {
                    b.HasOne("EFCore_12_Samurai_01.Models.Category", "Category")
                        .WithMany("Users")
                        .HasForeignKey("CategoryId");

                    b.HasOne("EFCore_12_Samurai_01.Models.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId");
                });
#pragma warning restore 612, 618
        }
    }
}
