// <auto-generated />
using System;
using MVC_2019_09_04_Fluent_with_date;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVC_2019_09_04_Fluent_with_date.Migrations
{
    [DbContext(typeof(LogItemDbContext))]
    partial class LogItemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MVC_2019_09_04_Fluent_with_date.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .IsRequired();

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("MVC_2019_09_04_Fluent_with_date.Log", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("LogDate");

                    b.Property<int>("LogItemId");

                    b.Property<int>("UserId");

                    b.HasKey("LogId");

                    b.HasIndex("LogItemId");

                    b.HasIndex("UserId");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("MVC_2019_09_04_Fluent_with_date.LogItem", b =>
                {
                    b.Property<int>("LogItemId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryId");

                    b.Property<string>("LogItemDescription")
                        .IsRequired();

                    b.Property<int>("LogItemPoints");

                    b.HasKey("LogItemId");

                    b.HasIndex("CategoryId");

                    b.ToTable("LogItems");
                });

            modelBuilder.Entity("MVC_2019_09_04_Fluent_with_date.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MVC_2019_09_04_Fluent_with_date.Log", b =>
                {
                    b.HasOne("MVC_2019_09_04_Fluent_with_date.LogItem", "LogItem")
                        .WithMany("Logs")
                        .HasForeignKey("LogItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MVC_2019_09_04_Fluent_with_date.User", "User")
                        .WithMany("Logs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MVC_2019_09_04_Fluent_with_date.LogItem", b =>
                {
                    b.HasOne("MVC_2019_09_04_Fluent_with_date.Category", "Category")
                        .WithMany("LogItems")
                        .HasForeignKey("CategoryId");
                });
#pragma warning restore 612, 618
        }
    }
}
