// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace EFCore_12_Samurai_01.Models
{
    public partial class Categories
    {
        public Categories()
        {
            Users = new HashSet<Users>();
        }

        public int CategoryId { get; set; }
        public string CategoryName { get; set; }

        public virtual ICollection<Users> Users { get; set; }
    }
}