// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace EFCore_12_Samurai_01.Models
{
    public partial class Testing
    {
        public int TestingId { get; set; }
        public string TestingName { get; set; }
    }
}