// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace EFCore_12_Samurai_01.Models
{
    public partial class Users
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public int? CategoryId { get; set; }
        public int? CompanyId { get; set; }

        public virtual Categories Category { get; set; }
        public virtual Companies Company { get; set; }
    }
}