//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace to_do_02
{
    using System;
    using System.Collections.Generic;
    
    public partial class Todo
    {
        public int TaskID { get; set; }
        public string FirstName { get; set; }
        public string Task { get; set; }
        public bool Done { get; set; }
        public Nullable<System.DateTime> DoneDate { get; set; }
    }
}
