//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Migration_01_Console
{
    using System;
    using System.Collections.Generic;
    
    public partial class MigrationTest
    {
        public int MigrationTestId { get; set; }
        public string MigrationTestName { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
    }
}
